config/routes.rb
RentAPad::Application.routes.draw do
  resources :users, :hoods, :messages
  get '/about' => 'home#about'
  get '/faq' => 'home#faq'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  root :to => 'home#index'
end

app/models/hood.rb
# == Schema Information
#
# Table name: hoods
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  position :integer
#

class Hood < ActiveRecord::Base
  has_and_belongs_to_many :users

  def prior
    if position == 1
      Hood.find_by(position: 34)
    else
      Hood.find_by(position: position - 1)
    end
  end

  def next
    if position == 34
      Hood.find_by(position: 1)
    else
      Hood.find_by(position: position + 1)
    end
  end
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  subject    :string(255)
#  body       :text
#  user_id    :integer
#  contact_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact, class_name: 'User', inverse_of: :messages
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  password_digest :string(255)
#  name            :string(255)
#  age             :integer
#  gender          :string(255)
#  email           :string(255)
#  image           :text
#  description     :text
#  occupation      :string(255)
#  sociability     :integer
#  sleep_hours     :integer
#  is_smoker       :boolean
#  cooks           :string(255)
#  pets            :string(255)
#  roommate        :text
#  max_rent        :decimal(, )
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#


class User < ActiveRecord::Base
  has_secure_password
  serialize :roommate, Hash
  has_and_belongs_to_many :hoods
  has_many :messages
  has_many :contacts, through: :messages
  validates :name, presence: true, length: {minimum: 2}
  validates :email, presence: true, length: {minimum: 2}

  def received_messages
    Message.where(contact_id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authentication
  private
  def authentication
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end
  def ensure_logged_in
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to(users_path) if @auth.present?
  end
  def about
  end
  def faq
  end
end

app/controllers/hoods_controller.rb
class HoodsController < ApplicationController
  def index
    @hoods = Hood.all.order(:position)
  end
  def show
    @hood = Hood.find(params[:id])
    populate_demographics_info
  end

  private

  def populate_demographics_info
    begin
      info = HTTParty.get("http://www.zillow.com/webservice/GetDemographics.htm?zws-id=#{ENV['ZWS_ID']}&state=NY&city=NewYork&neighborhood=#{@hood.name.gsub(' ','')}")
      @income = info['demographics']['response']['pages']['page'][2]['tables']['table'][0]['data']['attribute'][0]['values']['neighborhood']['value']['__content__']
      @age = info['demographics']['response']['pages']['page'][2]['tables']['table'][0]['data']['attribute'][3]['values']['neighborhood']['value']
      @size = info['demographics']['response']['pages']['page'][2]['tables']['table'][0]['data']['attribute'][5]['values']['neighborhood']['value']
      @commute = info['demographics']['response']['pages']['page'][2]['tables']['table'][0]['data']['attribute'][6]['values']['neighborhood']['value']
    rescue => e
      raise "An error occurred!"
      puts e
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = @auth.received_messages
  end
  def new
    @message = Message.new
  end
  def create
    Message.create(:subject=>params[:subject],:body=>params[:body],:contact_id=>params[:contact_id],:user_id=>params[:user_id])
  end
  def destroy
    message = Message.find(params[:id])
    message.delete
    @messages = @auth.received_messages
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to(root_path)
    else
      flash[:notice] = 'Invalid login, try again.'
      redirect_to(login_path)
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_logged_in, :except => [:new, :create]
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def edit
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(root_path)
    else
      render :new
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to(@user)
    else
      render :new
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def intellinav
    links = ""
    if @auth.present?
      num = @auth.received_messages.count.to_s
      links += "<li>#{link_to 'Inbox (' + num + ')', messages_path}</li>"
      links += render :partial => 'layouts/hoodnav'
      links += render :partial => 'layouts/usernav'
    else
      links += "<li>#{link_to('Create Account', new_user_path)}</li>"
      links += "<li>#{link_to('Login', login_path)}</li>"
    end
  end
end

app/views/home/about.html.erb
<!-- Main Page Content and Sidebar -->

  <div class="row">

    <!-- Main Blog Content -->
    <div class="nine columns" role="content">

      <article>

        <h3>About Rent-A-Pad</h3>

        <div class="row", id='weird_row'>
          <div class="six columns">
            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa.</p>
            <p>Boudin aliqua adipisicing rump corned beef. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
          </div>
          <div class="six columns">
            <%= image_tag 'box_movers.jpg' %>
          </div>
        </div>

        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

      </article>

    </div>

    <!-- End Main Content -->


    <!-- Sidebar -->

    <aside class="three columns">

      <h5>Categories</h5>
      <ul class="side-nav">
        <li><a href="#">News</a></li>
        <li><a href="#">Code</a></li>
        <li><a href="#">Design</a></li>
        <li><a href="#">Fun</a></li>
        <li><a href="#">Weasels</a></li>
      </ul>

      <div class="panel">
        <h5>Featured</h5>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>
        <a href="#">Read More &rarr;</a>
      </div>

    </aside>

    <!-- End Sidebar -->
  </div>

  <!-- End Main Content and Sidebar -->

app/views/home/faq.html.erb
<div class="row">

    <!-- Main Content Section -->
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="nine columns push-three">

      <h3>Frequently Asked Questions <small>And Frequently Given Answers</small></h3>
      <ol>
        <li>Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short loin?</li>
        <p>Venison tail chuck pork chop, andouille ball tip beef ribs flank boudin bacon. Salami andouille pork belly short ribs flank cow. Salami sirloin turkey kielbasa. Sausage venison pork loin leberkas chuck short loin, cow ham prosciutto pastrami jowl. Ham hock jerky tri-tip, fatback hamburger shoulder swine pancetta ground round. Tri-tip prosciutto meatball turkey, brisket spare ribs shankle chuck cow chicken ham hock boudin meatloaf jowl.</p>

        <li>Ground round pastrami pork loin tenderloin jerky?</li>
        <p>Jerky spare ribs biltong, ham hock ham capicola pork. Jerky turducken pork, meatloaf sausage capicola swine corned beef turkey short loin. Tongue prosciutto pork loin, ground round spare ribs venison kielbasa strip steak.</p>

        <li>Hamburger bresaola turkey t-bone, leberkas salami pork chop ham hock beef ribs?</li>
        <p>Rump biltong meatball venison, short ribs pork loin shank shankle corned beef beef?<p>
        <li>Cow salami jowl short loin hamburger fatback?</li>
        <p>Short ribs pork belly shoulder pastrami drumstick salami corned beef ham hock bresaola. Swine filet mignon cow sausage ball tip. Cow ribeye ground round, sausage pork loin pig beef ball tip turkey boudin.</p>

        <li>Prosciutto ball tip filet mignon andouille frankfurter chicken rump sausage meatball?</li>
        <p>Filet mignon meatloaf ground round andouille ham hock pork. Bresaola short loin meatball chuck hamburger pig. Turkey venison chuck, tongue fatback tail swine jerky corned beef shank kielbasa prosciutto ribeye ham tri-tip. Rump bacon pork belly meatloaf shoulder short loin meatball kielbasa pork loin tongue bresaola brisket corned beef jowl prosciutto. Beef ribs shankle short ribs pork belly corned beef fatback pork chop tongue biltong boudin strip steak sirloin meatloaf pancetta.</p>
    </ol>
    </div>


    <!-- Nav Sidebar -->
    <!-- This is source ordered to be pulled to the left on larger screens -->
    <div class="three columns pull-nine">

      <ul class="side-nav">
        <li><a href="#">Section 1</a></li>
        <li><a href="#">Section 2</a></li>
        <li><a href="#">Section 3</a></li>
        <li><a href="#">Section 4</a></li>
        <li><a href="#">Section 5</a></li>
        <li><a href="#">Section 6</a></li>
      </ul>

      <p><%= image_tag 'for_rent.jpg' %></p>

    </div>

  </div>

app/views/home/index.html.haml
.row#hello
  .twelve.columns
    %h1 Welcome to Rent-A-Pad!
    #home_pic
    #login
    #home_links
      = link_to('Create Account', new_user_path, :class => 'large button radius success', :id =>'account_button')
      = link_to('Login', '#', :class => 'large button radius', :id => 'login_button', :"data-reveal-id" =>'modal')
#modal.reveal-modal{:class => "small"}
  %h2 Login
  = form_tag '/login' do
    = label_tag 'email'
    = text_field_tag 'email', nil, :autofocus => true
    = label_tag 'password'
    = password_field_tag 'password'
    = submit_tag 'Login to Rent-A-Pad', :class => 'button radius small'
  %a.close-reveal-modal ×

app/views/hoods/index.html.haml
.row
  .four.columns
    %ul#hood_links
      - @hoods.each do |hood|
        %li
          = link_to hood.name.gsub("_", " "), hood
          = image_tag hood.image, :class => 'hide'
        %br
  .eight.columns
    #map
      = image_tag 'maps/neighborhood_map.jpg', :id=>'main_map'

app/views/hoods/show.html.haml
.row
  .seven.columns
    %h1= @hood.name
    = image_tag @hood.image, :class=>'maps'
    %br
    %br
    = link_to 'Back', hoods_path
  .five.columns
    %h3 Demographics
    %h6
      Provided by
      = link_to 'Zillow', 'http://www.zillow.com', :target=>'_blank'
    %ul
      %li
        = "Median Household Income: #{number_to_currency(@income)}"
      %li
        = "Median Age: #{@age}"
      %li
        = "Average Household Size: #{number_with_precision(@size, :precision=>2)}"
      %li
        = "Average Commute Time: #{@commute.to_i.round} minutes"
    - if @hood.users.any?
      - if @auth.present?
        %h5 R-A-P users who would like to live here:
        %ul
          - @hood.users.order(:name).each do |user|
            %li
              = link_to user.name, user
      - else
        %h5= "#{@hood.users.count} R-A-P users would like to live here."
    %br
    %br
    = image_tag ('arrow_left.png')
    = link_to "#{@hood.prior.name}", @hood.prior
    |
    = link_to "#{@hood.next.name}", @hood.next
    = image_tag 'arrow_right.png'

app/views/layouts/_hoodnav.html.haml
%li.has-dropdown
  = link_to 'Neighborhoods', hoods_path
  %ul.dropdown
    %li= link_to 'All', hoods_path
    - Hood.all.order(:name).each do |hood|
      %li= link_to hood.name, hood

app/views/layouts/_nav.html.haml
.row
  .twelve.columns
    %nav.top-bar
      %ul.top-bar
        %li.name
          %h1= link_to 'R-A-P', root_path
        %li.toggle-topbar
          = link_to '#'
      %section
        %ul.left
          %li= link_to 'Home', root_path
          %li= link_to 'About', about_path
          %li= link_to 'FAQ', faq_path
        %ul.right
          != intellinav

app/views/layouts/_usernav.html.haml
%li.has-dropdown
  %a{href: '#'}
    #navpic{style: "background-image:url('#{asset_path @auth.image}')"}
  %ul.dropdown
    %li= link_to 'See Profile', user_path(@auth)
    %li= link_to 'Edit Profile', edit_user_path(@auth)
    %li= link_to 'Logout', login_path, method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />

  <title>Welcome to Rent-A-Pad</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav><%= render :partial => 'layouts/nav' %></nav>
  <%= yield %>
  <!-- Footer -->

  <footer class="row">
    <div class="twelve columns">
      <hr />
      <div class="row">
        <div class="six columns">
          <p>&copy; SMM</p>
        </div>
        <div class="six columns">
          <ul class="link-list right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'FAQ', faq_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/messages/_inbox.html.haml
- if @messages == []
  No messages
- else
  %table#inbox
    %tr
      %th From
      %th Subject
      %th Body
      %th Reply
      %th Delete
    - @messages.each do |message|
      - sender = User.where(:id => message.user_id).first
      %tr
        %td= link_to(sender.name, user_path(sender), :title => sender)
        %td.hide= image_tag asset_path sender.image
        %td= message.subject
        %td= message.body
        %td
          %a{:"data-reveal-id" =>"user_#{sender.id}"}
            = image_tag 'comments.png', :class => 'inbox_links'
        %td
          %a{:"data-reveal-id" => "message_#{message.id}"}
            = image_tag 'cross.png', :class => 'inbox_links'
      .reveal-modal[sender]
        = form_tag "/messages", :remote => true do
          %h4= "Message to #{sender.name}"
          = label_tag 'subject'
          = text_field_tag 'subject', "RE: #{message.subject}", :autofocus => true
          = label_tag 'body', 'Message Body'
          = text_area_tag 'body'
          = hidden_field_tag 'contact_id', sender.id
          = hidden_field_tag 'user_id', @auth.id
          = submit_tag nil, :class=>"button radial messages"
        %a.close-reveal-modal &#215;
      .reveal-modal[message]
        %h4 Are you sure you want to delete this message?
        =button_to_function('Cancel', 'hide_modal()', :class => 'button radial cancel_button')
        =button_to 'Delete', message, :method => :delete, :remote => true, :class => 'button radial alert delete_button'
        %a.close-reveal-modal &#215;

app/views/messages/destroy.js.erb
hide_modal();
$('nav').empty().append('<%=j render :partial => 'layouts/nav' %>')
$('#table').empty().append('<%=j render :partial => 'inbox' %>')

app/views/messages/index.html.haml
.row
  .twelve.columns
    #table
      = render :partial => 'inbox'

app/views/session/new.html.haml
.row
  .five.columns
    = form_tag '/login' do
      = label_tag 'email'
      = text_field_tag 'email', nil, :autofocus => true
      = label_tag 'password'
      = password_field_tag 'password'
      = submit_tag 'Login to Rent-A-Pad', :class => 'button radius small'
  .seven.columns

app/views/users/_longform.html.haml
= form_for(@user) do |f|
  .seven.columns
    - if @user.errors.any?
      #error_explanation
        %h2
          = pluralize(@user.errors.count, "error")
          prohibited this user from being saved:
          %ul
            - @user.errors.full_messages.each do |msg|
              %li= msg
    .field
      %h4 Your details
      = f.label :email
      = f.text_field :email, :autofocus => true
      = f.label :name, 'First Name'
      = f.text_field :name
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.label :age
      = f.text_field :age
      = f.label :gender
      = f.text_field :gender
      = f.label :image
      = f.text_field :image
      = f.label :description
      = f.text_area :description
      = f.label :occupation
      = f.text_field :occupation
      = f.label :sleep_hours
      %table
        %tr
          %td
            = f.label :early
            = f.radio_button(:sleep_hours, 1, :class =>'radios')
          %td
            = f.label :late
            = f.radio_button(:sleep_hours, 2, :class =>'radios')
          %td
            = f.label :nocturnal
            = f.radio_button(:sleep_hours, 3, :class =>'radios')
      = f.label :sociability, 'Hosts friends'
      %table
        %tr
          %td
            = f.label :never
            = f.radio_button(:sociability, 0, :class => 'radios')
          %td
            = f.label :rarely
            = f.radio_button(:sociability, 1, :class => 'radios')
          %td
            = f.label :sometimes
            = f.radio_button(:sociability, 2, :class => 'radios')
          %td
            = f.label :often
            = f.radio_button(:sociability, 3, :class => 'radios')
      = f.label :is_smoker, 'Smoking habits'
      %table
        %tr
          %td
            = f.label :'non-smoker'
            = f.radio_button(:is_smoker, false, :class => 'radios')
          %td
            = f.label :smoker
            = f.radio_button(:is_smoker, true, :class => 'radios')
      = f.label :pets
      = select_tag 'pets', "<option>Have</option><option>Want</option><option>Don't Want</option><option>Don't care</option>".html_safe, :class => 'selects'
      %br
      %br
      = f.label :max_rent, 'Maximum Monthly Rent Payment'
      = f.text_field :max_rent
      %h4
        Your roommate search
        %small (All fields are optional)
      = f.label 'roommate[:max_age]', 'Age Maximum'
      = number_field_tag 'roommate[:max_age]', nil, :min => 18
      = f.label 'roommate[:min_age]', 'Age Minimum'
      = number_field_tag 'roommate[:min_age]', nil, :min => 18
      = f.label 'roommate[:gender]', 'Gender'
      = select_tag 'roommate[:gender]', "<option></option><option>Male</option><option>Female</option><option>Either</option>".html_safe, :class => 'selects'
      = f.label 'roommate[:employed]', 'Employed'
      = select_tag 'roommate[:employed]', "<option></option><option>True</option><option>False</option>".html_safe, :class => 'selects'
  .five.columns
    %h4
      %span#neighborhood{:title=>'Neighborhood'}= link_to 'Neighborhood(s)', hoods_path
      in which you'd like to live
    %ul
      - Hood.order(:name).each do |hood|
        %li.checkboxes{:title=>'checkbox'}
          .hide= check_box_tag 'user[hood_ids][]', hood.id, hood.in?(@user.hoods.to_a)
          %span.hood_name
            = "#{hood.name} /"
          = image_tag hood.image, :class => 'hide'
  = f.submit nil, :class => 'button success radius tiny'

app/views/users/_shortform.html.haml
.five.columns
  = form_for(@user) do |f|
    - if @user.errors.any?
      #error_explanation
        %h2
          = pluralize(@user.errors.count, "error")
          prohibited this user from being saved:
          %ul
            - @user.errors.full_messages.each do |msg|
              %li= msg
    .field
      = f.label :email
      = f.text_field :email, :autofocus => true
      = f.label :name, 'First Name'
      = f.text_field :name
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
    = f.submit nil, :class => 'button success radius tiny'

app/views/users/edit.html.haml
.row
  .twelve.columns
    %h1 Edit Profile
.row
  = render :partial => 'longform'

app/views/users/index.html.haml
.row
  .twelve.columns
    .row
      - @users.each do |user|
        - if user.id != @auth.id
          .three.mobile-one.columns
            %a{:href => user_path(user)}/
            .thumbs{:style => "background-image:url('#{asset_path user.image}')"}
            .panel
              %h5= link_to user.name, user
              %h6.subheader= user.age
              %h6.subheader= user.gender
              %h6.subheader= number_to_currency(user.max_rent)
              %a{:"data-reveal-id" =>"user_#{user.id}"}
                .mail_pic
        .reveal-modal[user]
          = form_tag "/messages", :remote => true do
            %h4= "Message to #{user.name}"
            = label_tag 'subject'
            = text_field_tag 'subject', nil, :autofocus => true
            = label_tag 'body', 'Message Body'
            = text_area_tag 'body'
            = hidden_field_tag 'contact_id', user.id
            = hidden_field_tag 'user_id', @auth.id
            = submit_tag nil, :class=>"button radial messages"
          %a.close-reveal-modal &#215;

app/views/users/new.html.haml
.row
  .twelve.columns
    %h1 New User
.row
  = render :partial => 'shortform'

app/views/users/show.html.haml
.row
  .six.columns
    %h3 About Me
    %ul
      %li
        %b Name:
        = @user.name
      %li
        %b Age:
        = @user.age
      %li
        %b Gender:
        = @user.gender
      %li
        %b Description:
        = @user.description
      %li
        %b Occupation:
        = @user.occupation
      %li
        %b Sleep Hours:
        - case @user.sleep_hours
          - when 1
            Early
          - when 2
            Late
          - when 3
            Nocturnal
      %li
        %b Hosts friends:
        - case @user.sociability
          - when 0
            Never
          - when 1
            Rarely
          - when 2
            Sometimes
          - when 3
            Often
      %li
        %b Smoking habits:
        = @user.is_smoker == true ? "Smoker" : "Non-smoker"
      %li
        %b Pets:
        = @user.pets
      %li
        %b Maximum Rent:
        = number_to_currency(@user.max_rent)
      %li
        %b Desired Neighborhoods:
        - @user.hoods.each do |hood|
          %ul
            %li= link_to hood.name, hood

    %h3 My Roommate Search
    %ul
      - if @user.roommate[:min_age].present?
        %li
          %b Age Minimum:
          = @user.roommate[:min_age]
      - if @user.roommate[:max_age].present?
        %li
          %b Age Maximum:
          = @user.roommate[:max_age]
      - if @user.roommate[:gender].present?
        %li
          %b Gender:
          = @user.roommate[:gender]
      - if @user.roommate[:is_smoker].present?
        %li
          %b Smoking habits:
          = @user.roommate[:is_smoker]
      - if @user.roommate[:employed].present?
        %li
          %b Employed:
          = @user.roommate[:employed]
    - if @user.id == @auth.id
      = link_to 'Edit', edit_user_path(@user)
      |
    = link_to 'Back', users_path
  .six.columns
    .show{:style => "background-image:url('#{asset_path @user.image}')"}
    .clear
    - if @user.id != @auth.id
      %h4
        %table
          %tr
            %td Message me!
            %td
              %a{:"data-reveal-id" =>"user_#{@user.id}"}
                .mail_pic_show
.reveal-modal[@user]
  = form_tag "/messages", :remote => true do
    %h4= "Message to #{@user.name}"
    = label_tag 'subject'
    = text_field_tag 'subject', nil, :autofocus => true
    = label_tag 'body', 'Message Body'
    = text_area_tag 'body'
    = hidden_field_tag 'contact_id', @user.id
    = hidden_field_tag 'user_id', @auth.id
    = submit_tag nil, :class=>"button radial messages"
  %a.close-reveal-modal &#215;